sudo: true
language: node_js
node_js:
  - "0.10"
  - "0.12"
  - "1"
  - "2"
  - "3"
  - "4"
  - "5"
  - "6"
script:
  - node --version
  - npm --version
  - npm test
  - node_modules/karma/bin/karma start my.conf.js --single-run
before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
before_script:
  - npm install -g gulp jshint@2.x
  - npm install