sudo: true
language: node_js
node_js:
  - "0.8"
  - "0.10"
  - "0.12"
  - "1"
  - "2"
  - "3"
  - "4"
  - "5"
  - "6"
before_script:
  - npm install -g gulp
  - npm install
script:
  - node --version
  - npm --version
  - npm test